---
- name: Check if the caddy file already exists (Will not overwrite if it exists)
  stat:
    path: /etc/caddy/Caddyfile
  register: cfstat

- name: Create caddy service for laravel project
  include_role:
    name: caddy_ansible.caddy_ansible
    public: yes
  vars:
    caddy_user: caddy
    caddy_group: caddy
    caddy_systemd_capabilities_enabled: true
    caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
    caddy_config: |
        {{ fqdn }}
        php_fastcgi 127.0.0.1:9000
        encode gzip
        root * {{ larapub }}
        file_server
  when: not cfstat.stat.exists

