---
- name: Create caddy service for laravel project
  include_role:
    name: caddy_ansible.caddy_ansible
    public: yes
  vars:
    caddy_systemd_capabilities_enabled: true
    caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
    caddy_config: |
        {{ fqdn }}
        encode gzip
        file_server browse {
            root {{ larapub }}
        }

