---

- name: Make sure we're python3
  apt:
    name: [ 'python-is-python3' ]
    state: present
    update_cache: yes

- name: Install required system packages
  package: 
    name: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools' ]
    state: present

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable
    state: present

- name: Create /var/lib/docker partition
  parted:
    device: "{{ dockerdisk }}"
    number: 1
    state: present
    part_type: primary
  tags:
    - partition
  when: dockerdisk is defined

- name: Create /var/lib/docker filesystem
  filesystem:
    dev: "{{ dockerdisk }}1"
    fstype: xfs
  tags:
    - partition
  when: dockerdisk is defined

- name: Mount /var/lib/docker filesystem
  mount:
    src: "{{ dockerdisk }}1"
    path: /var/lib/docker
    state: mounted
    fstype: xfs
  tags:
    - partition
  when: dockerdisk is defined

- name: Install docker
  package: 
    name: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]
    state: present

- name: Make sure docker override exists
  file: path=/etc/systemd/system/docker.service.d state=directory
  tags: systemd

- name: Put systemd override in place
  copy: src=override.conf dest=/etc/systemd/system/docker.service.d/override.conf
  notify: systemctl-reload
  tags: systemd

- name: Change docker default network to use RFC6598 ranges
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: restart-docker


