---
- name: Install PHP
  include_role:
    name: geerlingguy.php-versions
    public: yes
  vars:
    php_version: "8.1"

- name: Install default PHP Packages
  package:
    name:
      [
        "php{{ php_version }}-cli",
        "php{{ php_version }}-xml",
        "php{{ php_version }}-bcmath",
        "php{{ php_version }}-gd",
        "php{{ php_version }}-intl",
        "php{{ php_version }}-mbstring",
        "php{{ php_version }}-mysql",
        "php{{ php_version }}-sqlite3",
        "php{{ php_version }}-zip",
        "php{{ php_version }}-soap",
        "php{{ php_version }}-yaml",
        "php{{ php_version }}-curl",
        "libapache2-mod-php{{ php_version }}",
      ]
    state: present

- name: Install Composer
  include_role:
    name: composer

- name: Install JQ
  package:
    name: jq
    state: present

