---
- name: Set our php version to be 8.1
  include_role:
    name: geerlingguy.php-versions
    public: yes
  vars:
     php_version: "8.1"

- name: Install PHP 8.1 finally.
  include_role:
    name: geerlingguy.php
    public: yes
  vars:
    php_version: "8.1"
    php_enable_webserver: false
    php_enable_php_fpm: true
    php_fpm_state: started
    php_fpm_enabled_on_boot: true

- name: Install default PHP Packages
  package:
    name:
      [
        "php{{ php_version }}-cli",
        "php{{ php_version }}-xml",
        "php{{ php_version }}-bcmath",
        "php{{ php_version }}-gd",
        "php{{ php_version }}-intl",
        "php{{ php_version }}-mbstring",
        "php{{ php_version }}-mysql",
        "php{{ php_version }}-sqlite3",
        "php{{ php_version }}-zip",
        "php{{ php_version }}-soap",
        "php{{ php_version }}-yaml",
        "php{{ php_version }}-curl",
        "php{{ php_version }}-redis",
      ]
    state: present

- name: Install Composer
  include_role:
    name: composer

- name: Install JQ
  package:
    name: jq
    state: present

